### ISSUE TITLE
Merge scripts in test/e2e2 and hack/demo-env

### ISSUE THREAD

**Issue by jannfis** [argoproj-labs/argocd-agent#244]
### Is your task related to a problem? Please describe.

Many of the scripts in `test/e2e2` and `hack/demo-env` feel (and probably are) redundant, as they do the same things:

* Setup a vcluster environment and install Argo CD in various degrees of completeness
* Start the principal from the current code base
* Start the agent(s) from the current code base

That makes changes to one or the other cumbersome, and both scripts will slowly drift apart.

### Describe the solution you'd like

It would be great if we can use one single set of scripts for both scenarios, e2e tests and the demo env.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by jopit** [comment]
I'll take a look at this.
